### ISSUE TITLE
config only works with virtuoso

### ISSUE THREAD

**Issue by nicky508** [architolk/Linked-Data-Theatre#15]
The configuration works only when it comes from Virtuoso. However the data is able to be provided by another not virtuoso sparql endpoint.

**Comment by architolk** [comment]
Nicky, did you follow the instructions in the config.xml file? (lines 71-75). We're using a GraphDB endpoint and it works ok.

**Comment by ehietanen** [comment]
I am having the same issue, when configurations are in Apache Jena Fuseki

**Comment by architolk** [comment]
Closed: the current regression test is tested against a RDF4j backend
