### ISSUE TITLE
index appearance stopt working

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [architolk/Linked-Data-Theatre#26]
Hello there,
Without an example I worked out a way to work with an index appearance. See http://hobby.wikixl.nl:8080/query/inf-begrippen?term=A.
Alas, after upgrading to the latest version it stopt working.
Must be doing something out of the ordinary.
Any suggestions?
Thanks Gerald

**Comment by joostaafjes** [comment]
Do you have a sample snippet of code that defines the IndexAppearance?

**Comment by architolk** [comment]
Gerald,
Your solution might work, but is actually a pretty hard way of doing stuff. I've added a tutorial of some basic usage of the IndexAppearance ([https://github.com/architolk/Linked-Data-Theatre/wiki/IndexAppearance](https://github.com/architolk/Linked-Data-Theatre/wiki/IndexAppearance)). I think this will help in your case. My advice would be to use this approach

**Comment by GeraldGrootRoessink** [comment]
Thanks that's better. Minor detail: when using xhtml:link "" for the 
curent page, if a gatenumber is used, it is lost.

Gerald

|xhtml:link "";|


Op 21-11-2016 om 12:44 schreef architolk:
