### ISSUE TITLE
Access Control should be configurable

### ISSUE THREAD

**Issue by dvh** [architolk/Linked-Data-Theatre#34]
The JSON-LD representations now return `Access-Control-Allow-Origin` headers which are hardcoded to `*` (anything). There should be an option to overrule this setting and change or remove these headers.

Also see:
- https://github.com/architolk/Linked-Data-Theatre/blob/79c46a1fbd0e57714304c1177156ba16fcb29003/src/main/webapp/WEB-INF/resources/apps/ldt/pipelines/query.xpl#L940
- https://github.com/architolk/Linked-Data-Theatre/blob/79c46a1fbd0e57714304c1177156ba16fcb29003/src/main/webapp/WEB-INF/resources/apps/ldt/pipelines/query.xpl#L973

In my usecase all response headers are handled via a proxy and I don't want the underlying components to return this header at all. Other usecases might involve disallowed origins so at least the `*` should be configurable.

**Comment by architolk** [comment]
This is solved by creating an option in the config.xml file. You can now specify: cors="no", which will remove the CORS headers.
