### ISSUE TITLE
examples on wiki do not work

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [architolk/Linked-Data-Theatre#52]
The examples on the wiki doet not work. See..
https://github.com/architolk/Linked-Data-Theatre/wiki

**Comment by architolk** [comment]
Gerald, which example doesn't work? There are a lot of examples on the wiki :-)

**Comment by GeraldGrootRoessink** [comment]
![image](https://user-images.githubusercontent.com/20146034/27256109-97ec180c-53ac-11e7-95c3-f72e5b0f9437.png)
