### ISSUE TITLE
NavbarAppearance does not show submenu's

### ISSUE THREAD

**Issue by JanDuo** [architolk/Linked-Data-Theatre#54]
The example as provided on [https://github.com/architolk/Linked-Data-Theatre/wiki/NavbarAppearance](url) does work correctly. But this works only because the Navbar**Search**Appearance is used. When this is changed to NavbarAppearance the submenu-items are listed as menu-items (from left to right) and the dropdownlist of the submenu becomes empty.
This seems a bug to me.
I'm using version 1.17.0 of LDT.

**Comment by architolk** [comment]
Solved in 1.18.1

**Comment by JanDuo** [comment]
Any idea when 1.18.1 will be released?

**Comment by architolk** [comment]
A couple of minutes ago

**Comment by JanDuo** [comment]
Installed 1.18.1 and the submenu's show up as expected in the NavbarAppearance. So it's solved.
