### ISSUE TITLE
how to show a newline character in the data?

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [architolk/Linked-Data-Theatre#56]
Transforming our metadata involves dealing with newline-characters. It is quite common in programming languages to use \n. I know about Markdown-appearence in LDT en it works fine, but not with this. Also \\n as suggested on the internet doesn't do the trick.  Is there a another way tot show a newline?

**Comment by architolk** [comment]
The problem might be that the \n is also replaced with a "normal" newline. However, markdown will work, but it expects two new lines. Please look at https://github.com/architolk/Linked-Data-Theatre/blob/master/examples/tests/MarkdownAppearance.ttl for an example.

**Comment by GeraldGrootRoessink** [comment]
Thanks for the tip. Did some tests:
First,  a warning: if you copy/paste this example you loose the blank lines. 
Second: With a blank line (in effect two consecutive /n)  Markdown will indeed act as promissed.
Third:  The "original" Markdown (John Gruber: two spaces before /n) also works, but is very counterintuïtive.  So lets forget that.
Fourth:  This /n/n gets lost if you demand json content. Wouldn't it be better if it was passed on in json?
Fifth: de number- and bullit-lists in your example are shown in LDT, but not as lists.

**Comment by GeraldGrootRoessink** [comment]
At this time we use turtle for serialization of rdf. With turtle \n works just fine.
