### ISSUE TITLE
Newlines as missing when response is JSON

### ISSUE THREAD

**Issue by JanDuo** [architolk/Linked-Data-Theatre#58]
This is somewhat related to issue #56. When newlines or tabs are included into Virtuoso (without any translation to \n, \r or \t) they show up correctly within Virtuoso and Linked Data Theatre.
When the result of the same SPARQL is formatted into Turtle or XML they again to show correctly. But when the response is formatted into JSON the newlines completely disappear. Tabs though will show up (Postman clearly marks them with a \t in the response of a GET).
Why are the newlines missing in a JSON response?
Or should I say: why are newline, carriage return and tab not replaced in JSON by their standard escape characters \n, \r and \t?

**Comment by architolk** [comment]
Newline is replaced by \n, see for example the result of the ConstructFormats test: https://github.com/architolk/Linked-Data-Theatre/blob/master/src/test/expected-results/result015.ld%2Bjson

**Comment by JanDuo** [comment]
Installed 1.18.1 and the JSON-response does contain \n and \t where expected.
So it's solved!
