### ISSUE TITLE
A SubmitAppearance on a FormAppearance shows all defined language-labels

### ISSUE THREAD

**Issue by JanDuo** [architolk/Linked-Data-Theatre#59]
When defining a button on a form with several language dependent rdfs:labels, the button shows up with all defined languages. I used the example as found on the [wiki](https://github.com/architolk/Linked-Data-Theatre/wiki/FormAppearance).
This happens on a system with a default language English and on another one with default language Dutch.
I'm using LDT 1.17.0 (and waiting for 1.8.1 to be released).

**Comment by architolk** [comment]
Fixed in 1.18.1

**Comment by JanDuo** [comment]
Installed 1.18.1 and it's solved now.
