### ISSUE TITLE
how to use format=json in a table appearance

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [architolk/Linked-Data-Theatre#74]
Sometimes format=json works with a table-appearance, and sometimes it doesn't.   See  for example:
* https://lod.duo.nl/rio/query/adressen?format=json   --> ok
* https://lod.duo.nl/rio/api/v1/distributie/adressen?format=json  --> not found
My hunch is that json-format for table-appearance only works when there is '/query/' in the URI. 
Otherwise  I can't figure out what's happening.

**Comment by TallTed** [comment]
The `format=json` argument is not the issue here.

Note that https://lod.duo.nl/rio/api/v1/distributie/adressen also gets a `404`...

I don't understand what you're trying to achieve, so cannot advise any further.

**Comment by GeraldGrootRoessink** [comment]
Sorry for the confusion.  I made a typo. It should be:
https://lod.duo.nl/rio/api/v0/distributie/adressen
This html table appearance does work in this second example The json-version does not.
The first example is also a table and there the json-version does work. 
It seems to me that Linked Data Theater treats both situation differently. I would like to know my options.

**Comment by TallTed** [comment]
Ah, I see!  When I visit https://lod.duo.nl/rio/api/v0/distributie/adressen with my browser, there's an [Excel](http://lod.duo.nl/rio/api/v0/distributie/adressen?representation=http%3A%2F%2Flod.duo.nl%2Frio%2Fstage%2FAdressenAPI&subject=http%3A%2F%2Flod.duo.nl%2Frio%2Fapi%2Fv0%2Fdistributie%2Fadressen&format=xlsx) link at the bottom-left -- `http://lod.duo.nl/rio/api/v0/distributie/adressen?representation=http%3A%2F%2Flod.duo.nl%2Frio%2Fstage%2FAdressenAPI&subject=http%3A%2F%2Flod.duo.nl%2Frio%2Fapi%2Fv0%2Fdistributie%2Fadressen&format=xlsx`.

If you change the last bit, from `&format=xlsx` to `&format=json`, I think you'll [get what you want](http://lod.duo.nl/rio/api/v0/distributie/adressen?representation=http%3A%2F%2Flod.duo.nl%2Frio%2Fstage%2FAdressenAPI&subject=http%3A%2F%2Flod.duo.nl%2Frio%2Fapi%2Fv0%2Fdistributie%2Fadressen&format=json).  Possibly this reveals the answer you seek?
