### ISSUE TITLE
sparql-filter with regex ignores $

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [architolk/Linked-Data-Theatre#77]
A sparql filter could look like this: filter regex(?result_label,"^BO$",'i').  It should only find exact matches of "BO".  It turns out it only finds things that start with "BO". ^ does the tric. Unexpectedly is also finds words like "BOER". You could try te regex in the searchbox here on this site: lod.duo.nl
Thanks for helping

**Comment by TallTed** [comment]
Is it possible for you to provide the full SPARQL query that's being executed?  Optimally, in a variant that may be immediately executed on DBpedia or other public Virtuoso-hosted SPARQL endpoint?

**Comment by TallTed** [comment]
@GeraldGrootRoessink - I have built a few queries that run against DBpedia, which appear to show Virtuoso handles regex with `$` and `^` properly. 

  [FILTER REGEX(?result_label,"BOER",'i')](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=SELECT+%3Fresult_label+%0D%0AWHERE+%0D%0A%7B+%0D%0A++%3Fs++rdfs%3Alabel++%3Fresult_label++.%0D%0A++FILTER+REGEX%28%3Fresult_label%2C%22BOER%22%2C%27i%27%29%0D%0A%7D+%0D%0AORDER+BY+%3Fresult_label+%0D%0ALIMIT+10&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on&run=+Run+Query+)

  [FILTER REGEX(?result_label,"^BOER",'i')](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=SELECT+%3Fresult_label+%0D%0AWHERE+%0D%0A%7B+%0D%0A++%3Fs++rdfs%3Alabel++%3Fresult_label++.%0D%0A++FILTER+REGEX%28%3Fresult_label%2C%22%5EBOER%22%2C%27i%27%29%0D%0A%7D+%0D%0AORDER+BY+%3Fresult_label+%0D%0ALIMIT+10&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on&run=+Run+Query+)

  [FILTER REGEX(?result_label,"BOER$",'i')](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=SELECT+%3Fresult_label+%0D%0AWHERE+%0D%0A%7B+%0D%0A++%3Fs++rdfs%3Alabel++%3Fresult_label++.%0D%0A++FILTER+REGEX%28%3Fresult_label%2C%22BOER%24%22%2C%27i%27%29%0D%0A%7D+%0D%0AORDER+BY+%3Fresult_label+%0D%0ALIMIT+10&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on&run=+Run+Query+)

  [FILTER REGEX(?result_label,"^BOER$",'i')](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=SELECT+%3Fresult_label+%0D%0AWHERE+%0D%0A%7B+%0D%0A++%3Fs++rdfs%3Alabel++%3Fresult_label++.%0D%0A++FILTER+REGEX%28%3Fresult_label%2C%22%5EBOER%24%22%2C%27i%27%29%0D%0A%7D+%0D%0AORDER+BY+%3Fresult_label+%0D%0ALIMIT+10&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on&run=+Run+Query+)


Can you please provide the complete version string (first "paragraph" of output from `virtuoso-iodbc-t -?` or `virtuoso-t -?`) for your Virtuoso instance?

**Comment by GeraldGrootRoessink** [comment]
Thanks for reacting,
For now I do not have access to virtuoso inner-workings. However, this is the sparql:

_select	?graph 	?class ?class_label ?result ?result_label
FROM NAMED <http://lod.duo.nl/doc/ontology/v0/Cdm>
FROM NAMED <http://lod.duo.nl/doc/ontology/v0/Agwb>
FROM NAMED <http://lod.duo.nl/doc/schemes>
where {
	graph ?graph {
		?result rdfs:label ?result_label.				 
                filter regex(?result_label,"@TERM@",'i')
		OPTIONAL {
			?result rdf:type ?class.
			OPTIONAL {?class rdfs:label ?class_label}
		}
		 FILTER (isIRI(?result))
	}
}_

I tried this at our sparql endpoint replacing @TERM@ with the options above and they work fine. So my hypothesis is , it is not Virtuoso that doing this, the $ gets lost in Linked Data Theater. 
Would you agree?

**Comment by TallTed** [comment]
@GeraldGrootRoessink - Yes, I think your testing confirms that LDT is somehow stripping the `$` from the query before it reaches Virtuoso. I think @architolk will need to look into this one.

(FWIW, you can also [get many version details from a Virtuoso instance through the SPARQL interface](http://vos.openlinksw.com/owiki/wiki/VOS/VirtCheckSvrVersionViaSparql).)
