### ISSUE TITLE
resource in table-appearance not clickable.

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [architolk/Linked-Data-Theatre#8]
The result of a query can obtain  an object.  An object can be a literal or a resource. If a resource I expect it to be clickable, shown as blue and underlined when hovered above.

Some resources are  clickable like an external link.  A resource inside LDT is not. See for example Denominatie en Instellingsoort in 
http://hobby.wikixl.nl:8080/query/bevoegdgezag/onderwijsinstellingen?subject=http%3A%2F%2Fwww.lod.duo.nl%2Fdoc%2FOnderwijsaanbod&BG=http%3A%2F%2Fwww.lod.duo.nl%2Foa%2Fid%2Fbevoegdgezag%2F10249

Possibly this can resolved be introducing an new kind of fragment appearance?

**Comment by architolk** [comment]
Gerard,

The columns Denominatie and Instellingsoort are linked to a variable that contains a literal (?denom), a literal is not clickable. To have the literal as a label and still be able to have a link, you should do something like:
select ?denom ?denom_label where {denom skos;prefLabel ?denom_label}

The "special" _label postfix for the variable will tell the LDT not to have an extra column, but to use the value of ?denom_label as the label for the column denom, and use the value of the variable ?denom as the link.
