### ISSUE TITLE
No feature for rdf:collections

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [architolk/Linked-Data-Theatre#9]
This example uses an rdf:collection tot define an enumaration (in Dutch waardenlijst)

http://hobby.wikixl.nl:8080/resource?subject=http%3A%2F%2Fwww.lod.duo.nl%2Fgwb%2Fid%2Fbegrip%2Fdenominatie

LDT does not show all available values but only the first and a blanknode refering to the rest

Possibly this  feature can be copied from the  ELDA source code.

**Comment by architolk** [comment]
Indeed, this should be supported. Two comments however:
1) You're query should fetch the whole collection (using property paths)
2) I'm a bit curious why you should use a collection in this case: multiple semanticRelations are perfectly possible, and will be rendered as a list in the appearance.

**Comment by architolk** [comment]
Actually, this is already supported by using property paths. See the example at https://github.com/architolk/Linked-Data-Theatre/blob/master/examples/tests/BlankNodes.ttl

**Comment by GeraldGrootRoessink** [comment]
Thanks. It does the trick.

**Comment by GeraldGrootRoessink** [comment]
Thanks, its working now

Gerald

Op 16-10-2016 om 15:48 schreef architolk:
